name: Run TS-InSpec-Objects E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Run TS-InSpec-Objects E2E Tests
    runs-on: ubuntu-24.04

    steps:
     - uses: actions/checkout@v5

     - name: Setup Node.js
       uses: actions/setup-node@v6
       with:
        node-version: 22
        cache: 'npm'

     - name: Install dependencies
       run: npm ci

     - name: Run e2e tests
       run: npm test
