name: Build and Release NPM to GPR (GitHub Package Registry)
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mitre'

      - name: Build the NPM Package
        run: |
          npm install
          rm -rf test
          npm run build

      - name: Pack all items that are published
        run: npm pack

      # Publish inspec-objects to GitHub Package Registry
      - name: Publish inspec-objects to GPR
        run: npm publish mitre-inspec-objects-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
